<a href="https://colab.research.google.com/github/acharvighnesha/gen_ai_usecases/blob/master/intro_to_collab.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [15]:
import torch

In [16]:
import numpy as np

In [8]:
mylist=[[1,2,3,4,5],[2,4,6,8,20]]
mylist

[[1, 2, 3, 4, 5], [2, 4, 6, 8, 20]]

In [18]:
tensor_2d=torch.randn(3,4)

In [19]:
tensor_2d

tensor([[ 1.6167,  0.0272,  0.8027,  0.0752],
        [-0.8173, -0.8105, -0.1511,  0.0271],
        [ 0.0524,  1.7547, -2.5745,  0.1535]])

In [20]:
my_torch1=torch.arange(10)

In [21]:
my_torch2=my_torch1.reshape(5,2)
my_torch2

tensor([[0, 1],
        [2, 3],
        [4, 5],
        [6, 7],
        [8, 9]])

In [24]:
my_torch2[2,:]

tensor([4, 5])